dimension.world0=*

dimension.world-1=minecraft:the_nether minecraft:nether blue_skies:everbright aether:the_aether ad_astra:glacio ad_astra:mars ad_astra:venus swplanets:mustafar swplanets:hot swplanets:mandalore swplanets:endor 

dimension.world1=minecraft:the_end minecraft:end blue_skies:everdawn twilightforest:twilight_forest

dimension.world_space = ad_astra:moon ad_astra:moon_orbit ad_astra:earth_orbit ad_astra:glacio_orbit ad_astra:mars_orbit ad_astra:mercury ad_astra:mercury_orbit ad_astra:venus_orbit swplanets:endor_orbit swplanets:hot_orbit swplanets:mandalore_orbit swplanets:mustafar_orbit
